import type { Metadata } from "next";
import "./globals.css";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import NavBar from "@/app/ui/NavBar";

import { montserrat } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "HlsVideo Test App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <AppRouterCacheProvider>
          <NavBar>
            {children}
          </NavBar>
        </AppRouterCacheProvider>
       </body>
    </html>
  );
}
