POST http://localhost:8080/events/1/register
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQHRlc3QuY29tIiwiZXhwIjoxNzA2NTA2NjAzLCJpZCI6MX0.MlUHclNj-LwmE6R6X_X7VNhdiexfAt7Nvga_qjafKAo
