PUT http://localhost:8080/events/3
content-type: application/json

{
    "name": "Updated Event",
    "description": "Updated Description",
    "location": "Updated Location",
    "datetime": "2025-01-01T00:00:00.000Z"
}
    