export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="text-[#fff] bg-[#1E1E1E] primary-[#EF5D70] secondary-[#EFD677] accent-[#EF9873]"
        >{children}</body>
    </html>
  )
}
